# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Spin Clockwise'), (1, 'Spin Counterclockwise')])),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Done'), (3, 'Failed')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
