# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='action',
            field=models.CharField(choices=[('CLOCKWISE', 'Spin Clockwise'), ('COUNTER_CLOCKWISE', 'Spin Counterclockwise')], max_length=25),
        ),
    ]
